### ISSUE TITLE
As a developer, I want to fix memory leaks, so I have a stable and working product in production.

### ISSUE THREAD

**Issue by glenflorendo** [yamovie/server#9]
Heroku Logs:
`Warning: connect.session() MemoryStore is not designed for a production environment, as it will leak memory, and will not scale past a single process.`

**Comment by samsaksfithian** [comment]
Moved to the yamovie/client issue list with the "back end" label, so that all the issues will be in the same backlog.

As such, this is now a duplicate of yamovie/client#195
